### PR TITLE
Update to mongoose 5.12

### PR DESCRIPTION
**Pull request by hasezoey**
PR because mongoose broke types in 5.12.1

Waiting before merge:

- [x] https://github.com/Automattic/mongoose/issues/10081

### CODE REVIEW

**Comment by realvikas** [comment]
Mongoose 5.12.4 is released which fixes https://github.com/Automattic/mongoose/issues/10046

**Comment by hasezoey** [comment]
it seems like 5.12.4 fixes the mentioned upgrade issues, but also brought:
- https://github.com/Automattic/mongoose/issues/10144

this can be "ts-ignored" (for now), but i wouldnt release 8.0 fully until this gets resolved

**Comment by ttsirkia** [comment]
It seems that https://github.com/Automattic/mongoose/pull/10228 has probably fixed the issue with https://github.com/Automattic/mongoose/issues/10144 ?

**Comment by hasezoey** [comment]
@ttsirkia yes i know, just didnt remove the ts-ignore yet (its not outside facing)

**Comment by hasezoey** [comment]
updated in 3cc88aeda1f1703e32605893a0ecf48f9656d1f6

**Pull request merged**
