### PR TITLE
Recommend against using Babel

### PR DESCRIPTION
**Pull request by dandv**
https://github.com/typegoose/typegoose/pull/229#issuecomment-629562131

### CODE REVIEW

**Comment by hasezoey** [comment]
i dont see any changes in this pr

**Comment by dandv** [comment]
The change was `(not recommended for testing with Jest - use `ts-jest` instead)`.

**Comment by hasezoey** [comment]
sorry, github didnt highlight this change for me

**Comment by dandv** [comment]
image

**Comment by hasezoey** [comment]
@dandv i know, but other times it would highlight it in darker green on what parts actually changed, and i could see an difference at the time is was looking (sorry)

**Pull request closed without merging**
