### PR TITLE
Add Support for nested GetClass

### LINKED ISSUE #89: Get original Class from NestedPath's
Is possible to get the Type Class from an object of DocumentType?

```
const car: DocumentType<Car> = await CarModel.find(...);
const constructorName = car.constructor.name;
console.log(constructorName); // "model"
```

`console.log` prints "model" and not "Car". I need the  constructor of the actual class.
Any help?

### PR DESCRIPTION
**Pull request by hasezoey**
add support to get the class from "any" Schema compiled with typegoose

fixes #89

---

~~Please note that this PR is just a "prototype" without actual tests~~

### CODE REVIEW

**Comment by hasezoey** [comment]
https://github.com/Automattic/mongoose/issues/8284

**Comment by hasezoey** [comment]
@fabioformosa does `utils.getClass` work for you?

**Comment by fabioformosa** [comment]
> @fabioformosa does `utils.getClass` work for you?

It would be perfect.

 I've tried to test if work, but in `typegoose.d.ts` I found only 
`export { getClassForDocument } from './internal/utils';` 
not also `getClass`

**Comment by hasezoey** [comment]
> I found only
> export { getClassForDocument } from './internal/utils';
> not also getClass

what do you mean by it? did you try this branch (Pull Request) or the master / npm package?

**Comment by fabioformosa** [comment]
I tried linking branch `r6/nestedGetClass` in my package.json

**Comment by hasezoey** [comment]
@fabioformosa yarn or npm? yarn is known to not run the `prepare` script

**Comment by hasezoey** [comment]
and just to be sure i updated to the latest master

**Comment by fabioformosa** [comment]
Look at this line https://github.com/typegoose/typegoose/blob/r6/nestedGetClass/src/typegoose.ts#L43

You're exporting only `getClassForDocument `, not also the new `getClass`.

**Comment by hasezoey** [comment]
> You're exporting only getClassForDocument , not also the new getClass.

thanks for noticing that, but `import { getClass } from "@typegoose/typegoose/lib/internal/utils` should work - could you test that?

**Comment by hasezoey** [comment]
anyway, in f87714379155ec79d7a8d59fced31ff90f152618 it is fixed - thanks for noticing

**Comment by fabioformosa** [comment]
Ok, tested. It works very fine.
According my opinion, you cpuld merge into the master.

**Pull request merged**
