### PR TITLE
Fix ref name

### PR DESCRIPTION
**Pull request by B-Stefan**
Fix we release Version 6.0.0 without this the refs feature will break. 

I would prefer to merge this before the 6.0.0 release. @hasezoey  what do you think?

### CODE REVIEW

**Comment by hasezoey** [comment]
Thanks, i still haven't found all places where it should be used

**Comment by hasezoey** [comment]
this pr made something that some users are reporting to not working anymore

**Comment by B-Stefan** [comment]
@hasezoey  Should we add some test cases to avoid this in the future?

**Comment by hasezoey** [comment]
it seems that this pr didnt cause it, sorry

(discord)

**Pull request merged**
