### PR TITLE
Array Validators & Transforms

### PR DESCRIPTION
**Pull request by hasezoey**
(move from original repo to this fork)

Events happened since the original PR:
- mongoose@5.7.0 released
- rebased onto `r6/master`
- upgraded to v6.0.0 "syntax"
Update 1: - fixed it now? but it is really hacky and not future proof...

so more or less all tests except 2 pass:
- biguser: expects array to be length 1, but got 0
- arrayvalidators: default dosnt work, as described in https://github.com/Automattic/mongoose/issues/8012#issuecomment-529763148

This PR might be a "breaking" change

### CODE REVIEW

**Comment by hasezoey** [comment]
The Array Validators now work, but is a bit hacky & not future proof, and might be even wrong

thats why i wait for https://github.com/Automattic/mongoose/issues/8012#issuecomment-531135713 to get a response

**Comment by hasezoey** [comment]
@fabioformosa & @B-Stefan if you both would have the time, could you two test it if it breaks something?

**Comment by hasezoey** [comment]
I will move this PR / feature / parity to an 6.x (unkown yet), because of the hackyness

**Comment by B-Stefan** [comment]
It seems that this could be a better way to support this feature https://github.com/typegoose/typegoose/issues/25

**Comment by hasezoey** [comment]
@B-Stefan do you mean this(#29) or #25 is better?

**Comment by B-Stefan** [comment]
you approach  #29! :) 
If this feature is complete I would be happy to contribute the discriminator feature for arrays.

**Comment by hasezoey** [comment]
Update from mongoose issue: as by [his comment](https://github.com/Automattic/mongoose/issues/8012#issuecomment-534325097), it seems like this approach i currently use is the only option, i still feel like this is hacky, but i think its not gonna change, so i will merge it

For anyone who find missing / wrong associated options, please report via a new issue, thanks

**Comment by hasezoey** [comment]
Current State:
Everything is working, thanks to https://github.com/Automattic/mongoose/issues/8012

***BUT*** 2 tests still fail, because 2 options are missing in mongoose, `minlength` and `maxlength` for `Schema.Types.String`, [stated in this comment](https://github.com/Automattic/mongoose/issues/8012#issuecomment-543383947)

otherwise, cleanup would be needed

**Comment by hasezoey** [comment]
The [last remaining issue in mongoose got solved](https://github.com/Automattic/mongoose/issues/8256), so now every test is green
And cleanup is done

**Comment by hasezoey** [comment]
As a note:

the semver check for mongoose "5.7.6" is made, because array validators only work on 5.7.5, and in version 5.7.6 the missing options were added

**Pull request merged**
