### PR TITLE
Fix decorator options mutating (fixes #55)

### LINKED ISSUE #55: [Bug] References in array schemas translate to Mixed instead of ObjectID
Hello,

References in array schemas translate to Mixed instead of ObjectID.

Consider the following code:

```typescript
export class ChatChannelGroup {
  @prop({ enum: ChatChannelGroupType, required: true })
  public type!: ChatChannelGroupType;

  @prop({ ref: TEvent, required: true })
  public id!: Ref<TEvent>;
}

export class ChatChannel {
  @arrayProp({ _id: false, items: ChatChannelGroup, required: true })
  public access_groups!: ChatChannelGroup[];
}
```

When inspecting `ChatChannel.schema.paths.access_groups.schema.paths.id` I get a type of instance Mixed:
```
    "id": {
      "path": "id",
      "instance": "Mixed",
      "validators": [
        {
          "message": "Path `{PATH}` is required.",
          "type": "required"
        }
      ],
      "getters": [],
      "setters": [],
      "options": {
        "required": true
      },
      "_index": null,
      "isRequired": true,
      "originalRequiredValue": true,
      "$isUnderneathDocArray": true
    }
  },
```

When passing the class instead of the class name on line https://github.com/typegoose/typegoose/blob/master/src/prop.ts#L116 it correctly translates into ObjectID:
```
    "_id": {
      "path": "_id",
      "instance": "ObjectID",
      "validators": [],
      "getters": [],
      "setters": [
        null
      ],
      "options": {
        "auto": true
      },
      "_index": null,
      "$isUnderneathDocArray": true
    }
```

Best regards

### PR DESCRIPTION
**Pull request by ChrisLahaye**
When a class has n properties using the same subclass, the
function `baseProp` is called n times for each property in subclass.

The function `baseProp` receives a parameter `rawOptions` which
should be copied as its being mutated later on. This is intended with
the statement:
```
rawOptions = Object.assign(rawOptions, {})
```
Although, this statement never changes the reference of `rawOptions`
with as result that the options are mutating. This causes the final schema
to be constructed without the options ref, itemsRef, refPath, etc when
the subclass is used more than once.

This commit fixes the mutation of the options.

Signed-off-by: Chris Lahaye <dev@chrislahaye.com>

### CODE REVIEW

**Comment by hasezoey** [comment]
one question before i merge:
why define the new "rawOptions" after the first buildSchema? just to keep it constitent with the name assignment?

**Comment by hasezoey** [comment]
@RyannGalea does this pr fix your issue?

**Comment by RyannGalea** [comment]
I have not tested this yet, I am hoping so!

**Comment by ChrisLahaye** [comment]
I will merge master and move the assignment.

> one question before i merge:
> why define the new "rawOptions" after the first buildSchema? just to keep it constitent with the name assignment?
> 
> _PS: could you update the branch to the latest master?_

You could place it before the buildSchema between line 55 and 56, but the original statement that was intended to copy the object was also place afterwards. 

Regarding the name consistency, you suggest naming the parameter back to `rawOptions` and then doing:
```
rawOptions = Object.assign({}, rawOptions);
```

The passed function in `data_1.decoratorCache.get(initname).decorators.set(key, () => {` may be executed multiple times, at least based on the following test: 

```
    let i = false;
    data_1.decoratorCache.get(initname).decorators.set(key, () => {
        if (i) throw new Error('eh this is thrown');
        else i = true;
```

Assume parameter `rawOptions` has reference <1> which has value `{ref: <99>, required: true}`.
The first execution of `rawOptions = Object.assign({}, rawOptions);` causes `rawOptions` to have reference <2> which copied the value `{ref: <99>, required: true}` of <1>. Later we delete the key ref, causing <2> to have value `{required: true}`. 
The second execution of `rawOptions = Object.assign({}, rawOptions);` causes `rawOptions` to have reference <3> which has copied the value `{required: true}` of <2>. This is wrong.

What we would like is the following.

Assume parameter `rawOptions` has reference <1> which has value `{ref: <99>, required: true}`.
The first execution of `const rawOptions = Object.assign({}, origOptions);` causes `rawOptions` to have reference <2> which copied the value `{ref: <99>, required: true}` of <1>. Later we delete the key ref, causing <2> to have value `{required: true}`. 
The second execution of `const rawOptions = Object.assign({}, origOptions);` causes `rawOptions` to have reference <3> which has copied the value `{ref: <99>, required: true}` of <1>. This is good.

This is what happened before this commit.

Assume parameter `rawOptions` has reference <1> which has value `{ref: <99>, required: true}`.
The first execution of `rawOptions = Object.assign(rawOptions, {});` causes `rawOptions` to still have reference <1> which has value `{ref: <99>, required: true}`. Later we delete the key ref, causing <1> to have value `{required: true}`. 
The second execution of `rawOptions = Object.assign(rawOptions, {});` causes `rawOptions` to still have reference <1> which has value `{required: true}`. This is wrong.

**Comment by hasezoey** [comment]
> Regarding the name consistency, you suggest naming the parameter back to rawOptions and then doing:

with that i meant the below statement for `name`, didnt thought of the replacement of the statement before this pr, sorry 

> The second execution of rawOptions = Object.assign(rawOptions, {}); causes rawOptions to still have reference <1> which has value {required: true}. This is wrong.

i mean i dont understand why in this should have the previous pointer, i mean like it is a differing function call and `Object.assign(rawOptions, {})` was meant so that "rawOptions" is always an object (and not an undefined or null or so)

---

anyway when this fixes these issues, i will merge it, even if i dont understand how these issues were caused

**Pull request merged**
