### PR TITLE
Models can be deleted so that they can be overwritten

### LINKED ISSUE #84: Need a method to delete an existing model
## Which feature

Delete model
https://mongoosejs.com/docs/api.html#mongoose_Mongoose-deleteModel

## Why do you want it

I want to overwrite existing models in certain use cases

### PR DESCRIPTION
**Pull request by Ben305**
Fixes #84

### CODE REVIEW

**Comment by hasezoey** [comment]
Thanks for adding it

some thing i have done:
- merged master (to be on the latest changes)
- added documentation
- added some errors & logs (for debugging)
- added tests for the errors
- added function "deleteModelWithClass" that accepts the class and find the name of it and runs "deleteModel"
- changed tests & collections so that they dont interfere with each other (added "NormalUser" class)

are you ok with these changes?

**Comment by Ben305** [comment]
@hasezoey Of course, I'm fine with that 👍 

Could you merge this and publish a beta-release?

**Comment by hasezoey** [comment]
> Could you merge this and publish a beta-release?

because it is based on 6.1.0-pre, it will be in 6.1.0-3

**Comment by hasezoey** [comment]
As a note: 6.1.0-3 is released

**Pull request merged**
