### PR TITLE
feat: register schema to existingMongoose

### LINKED ISSUE #356: Is it possible to use my mongoose instance in typegoose

### PR DESCRIPTION
**Pull request by Timmatt-Lee**
## What does the Enhancement do

support schema registration on existingMongoose instance

## Related Issues

-  fixes #356

### CODE REVIEW

**Comment by hasezoey** [comment]
i dont really understand your wording, but looking from the code you mean "Use existingMongoose.Schema Class instead of default Schema Class"

**Comment by Timmatt-Lee** [comment]
> i dont really understand your wording, but looking from the code you mean "Use existingMongoose.Schema Class instead of default Schema Class"

That's correct

**Review by hasezoey — CHANGES_REQUESTED** [review]
Some tests might be good

**Comment by Timmatt-Lee** [comment]
It seems like issue #356 has no error, I'll keep tracking on this issue. Once there is any issue related to this, i'll reopen it.

**Pull request closed without merging**
